### ISSUE TITLE
Wish to bind to 'sso' / 'keycloak'

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#1083]
Do we have samples which show how to bind an application(preferably a java application)  to keycloak ?

**Comment by growi** [comment]
I was playing around with keycloak and created a sample binding for the petclinic application. 
The example can be found [here](https://github.com/growi/service-binding-operator/tree/feature/keycloak-sample/samples/apps/spring-petclinic) .  To get it to work you need to build the petclinic image or use [mine](https://hub.docker.com/r/growi83/spring-petclinic-oauth2) (I extended the patch to include the oauth2 starter). The app will auto-config if the servicebinding is bound.  Otherwise a password is generated on startup. 
For the keycloak login flow to work it is REQUIRED that the keycloak ingress is accessible through http://keycloak.local .
The keycloak deployment creates a realm "Test" and the confidential client "petclinic". No realm users will be created.

If there is interest I can create a clean PR to integrate the example.

**Comment by baijum** [comment]
This looks good to me. Please send PR.

**Comment by growi** [comment]
I created PR #1122 that integrates the sample.

**Comment by filariow** [comment]
Closed based on community discussion for December the 1st
