### ISSUE TITLE
Unable to retrieve ClusterWorkloadResourceMapping error occurring in sandbox following 1.1.0 update

### ISSUE THREAD

**Issue by jeremyary** [redhat-developer/service-binding-operator#1172]
### What is the environment (Minikube, Openshift)?
OSD, Sandbox

### What is the SBO version used?
1.1.0

### What are the steps to reproduce this issue?
  1. User reports issue occurs when binding Deployment and DeploymentConfig targets via Topology view amid RHODA workflow

### What is the expected behaviour?
Binding should occur without issue and update bound target appropriately

### What is the actual behaviour?
Binding is failing to occur and error is showing on ServiceBinding.status

### Service Binding Operator Logs

{"level":"error","ts":1655409506.4610255,"logger":"controller.servicebinding","msg":"Reconciler error","reconciler group":"[binding.operators.coreos.com](http://binding.operators.coreos.com/)","reconciler kind":"ServiceBinding","name":"mongo-example-worker-dc-mongo-me-4249dc945a-dbsc","namespace":"midawson-2-dev","error":"Unable to retrieve ClusterWorkloadResourceMapping for type \"[apps.openshift.io/v1](http://apps.openshift.io/v1), Resource=deploymentconfigs\"","stacktrace":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/remote-source/service-binding-operator/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2%5Cn%5Ct/remote-source/service-binding-operator/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227)"}

### Additional Information (Screenshots, etc)

[Gist of ServiceBinding CR](https://gist.github.com/jeremyary/6ca16e5f7c409947a8b985f94f501404)'s causing issue on sandbox, including error status

Slack [thread link](https://kubernetes.slack.com/archives/C019LQYGC5C/p1655401378452969) of someone different reporting the same issue

cc @wtrocki per your request

**Comment by pmacik** [comment]
Ref: https://issues.redhat.com/browse/APPSVC-1135

**Comment by sadlerap** [comment]
I've managed to reproduce this behavior locally.  It definitely looks to be the case that if the service account that made the service binding doesn't have permissions to get CWRM (ClusterWorkloadResourceMapping) resources, it will fail exactly as has been shown in the bug reports we've been getting.

This definitely has implications regarding privilege escalation.  I think there are a few approaches to take here:

 - Always fetch CWRMs, regardless of if a user has permissions to or not.  Since they had permission to make a service binding, we should honor that request.
   - To me, this feels like a workaround for a rather strange case.  They had permissions to create a service binding, but not get a CWRM?  The solution here should be to grant your user more permissions, not change SBO.  That said, this is a sort of breaking change for users that were previously able to make service bindings, since now they require extra permissions to do so.
 - Default to PodSpec-compatible mappings if a user doesn't have sufficient privileges.  Since we weren't able to fetch a CWRM, we treat it like no CWRM was found, and SBO falls back to PodSpec.
   - This will definitely cause bindings to fail for a reason not necessarily apparent to the user when attempting to project bindings into a non-podspec-compatible workload.
 - Require users to have sufficient privileges to get CWRM resources.  This approach requires no changes to SBO.
   - With this approach, we need to add to our release notes for v1.1.x that users that want to make service bindings now require permissions to get CWRMs.

I think either 1 or 3 are correct approaches to take here, with 3 preferable.  2 has too many opportunities for misuse for it to be an acceptable solution.

**Comment by pmacik** [comment]
Keeping the issue open until RH released version is installed to the Developer Sandbox and confirmed that the solution indeed fixed the issue.

**Comment by pmacik** [comment]
@jeremyary SBO v1.1.1 (including the fix to this issue) in installed on the Developer Sandbox.. Could you please check that the issue is indeed fixed from your point of view? Thanks

**Comment by baijum** [comment]
The issue has been resolved in the DevSandbox.
