### ISSUE TITLE
Proposal: Add Post-Retrieve Hooks

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#154]
# Add Post-Retrieve Hooks

Prepared by: Akash Shinde(akshinde@redhat.com), Avni Sharma(avsharma@redhat.com)

## Abstract

This proposal aims to add support for custom hooks which would get executed before storing bindable variables in Secret.

## Motivation
There are use cases where we would need to update/process bindable variable and then store back to secrets.
One such a usecase we are going through is adding support of custom env variables.

### Architecture
![](https://i.imgur.com/xZmVAO3.png)

### Implementation

Current Retrieve() call
```
func (r *Retriever) Retrieve() error {
    
    ....
    
    Run []hooks
    
    return r.saveDataOnSecret()
}
```

Hook will accept the Retriever instance.
```
struct Hook interface {
    // This would run before storing secrets.
    Run(*Retriever) error
}
```

Then we can implement this hook to add support custom env variables.

##### CustomEnvHook

```
struct CustomEnvHook {
    Hook
}

func (c *CustomEnvHook) Run(r *Retriever) error {
 
    // TODO: Read SBR and figure out all custom env variables to bind
    // Add logic to prepare [key-value] of custom variables. Update r.Data
    // Then r.Data gets persisted.

}
```

## Pros
1. Keeps `Retrieve` modulerized-easy to use. 
2. Easy to test and maintain functional components.
3. Create re-usable, isolated components to avoid redundant logic.

## Cons
1. Implemented in a synchronized manner which might experience some delay.

**Comment by akashshinde** [comment]
@sbose78 basically you would get `retriever` instance to each and every hook which can perform any operation such as 
1. Altering environment variables before storing it to secret.
2. Since you get access to `retriever` you will have kube-connected rest client as well, so basically you can make any k8s resource.

**Comment by akashshinde** [comment]
`retriever` is being shared by all the hooks, so here we need to make sure one `Run()` doesn't disturb the `retriever`. It just should do it's work and write data without tampering the existing one
and then `retriever` gets passed down to next `Hook` and so on.

**Comment by otaviof** [comment]
Interesting design with post-retrieve hooks, good work folks! I wonder if instead of trying to employ post-retrieve hooks straight away, if we could tackle this situation by introducing a new component that Retrieve could interact with, and furthermore, a component that would be passed along in the reconcile workflow. 

Therefore, if we talk about the basic elements of this new component, I would suggest:

``` go
type EnvVar {
	// data is set during constructor and would contain all data relevant to the operator
	data map[struct]interface{}
}

func (e *EnvVar) Set("variable_name", "path") error {
	// goes through data and retrieve the data based on path informed (jsonpath)
	// store k/v in a local cache
}

func (e *EnvVar) Get("variable_name") (string, error) {
	// retrieve a variable from local cache
}

func (e *EnvVar) storeAsSecret() error {
	// render local cache as a k8s secret
}
```
Notice that this component would be fed with all relevant data in the operator scope, so it can be empowered to retrieve data using "JSONPath" type of approach, without having to manage everything the rest of the operator is already doing.

And therefore, `Retriever` could leverage this new component and be decoupled from the actual environment variable special logic by this fashion. A new component has advantages in terms of simplicity and that pays off medially in testability of the code base; assuming here that testing web-hooks would require a lot more complexity compared.

**Comment by isutton** [comment]
I have some questions:

1. What actions is expected for hook developers to perform on `Retriever` to justify it being an argument?
2. Since `hooks` is a slice, I expect one would declare hooks the same way as predicates, and also be able to chain them (pretty much the same sense as in a middle ware). Did you predict this use case in your initial design?

**Comment by isutton** [comment]
> I would think, the answer to my question would be:
> 
> Run() goes and collects information and populates the datastructure which eventually is the source of the contents of the binding secret.

This seems the next sensible decomposition of `Retriever`, and is in line with https://github.com/redhat-developer/service-binding-operator/pull/155 to solve _this particular issue_.

Just to clarify my view point and get into a baseline, my interpretation of a hook is a piece of code that might wrap a functionality adding behavior _before_ or _after_ the execution of the _main business logic_, whereas hooks as detailed in this proposal are indeed closer to collectors that could be potentially executed in parallel as long as each collectors don't overlap with data they provide.

I also think @otaviof suggestion has its merits, and is also aligned in principle with the collector idea.
