### ISSUE TITLE
Question: Can we use resourceRef to select application instead of matchLabels ?

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#227]
Since UI topology view would have direct access of the application DC, we can use `resourceRef` instead of `matchLabels` 

What are your thoughts @sbose78 @otaviof ?

Below is the SBR request created by devconsole UI internally 
```
  const serviceBindingRequest = {
    apiVersion: 'apps.openshift.io/v1alpha1',
    kind: 'ServiceBindingRequest',
    metadata: {
      name: sbrName,
      namespace,
    },
    spec: {
      applicationSelector: {
        resourceRef: sourceName,
        group: sourceGroup[0],
        version: sourceGroup[1],
        resource: modelFor(source.kind).plural,
      },
      backingServiceSelector: {
        group: targetResourceGroup[0],
        version: targetResourceGroup[1],
        kind: targetResourceKind,
        resourceRef: targetResourceRefName,
      },
    },
  };
```

UI SBR PR: https://github.com/openshift/console/pull/3065/files#diff-5c764acb551787fd095fe2442835a25bR4

**Comment by DhritiShikhar** [comment]
Ideally, the output of both the methods - `resourceRef` and `matchLabels` should be the same.
So, we **CAN** use `resourceRef` to select application instead of matchLabels.

Also, I would like to highlight that the code is written in a way that we look for presence of `resoureRef` first -> https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/binder.go#L55

**Comment by akashshinde** [comment]
closing this issue since this is already been handled.
