### ISSUE TITLE
Infinite loop while waiting for bound application to be available when binidng request is created first.

### ISSUE THREAD

**Issue by pmacik** [redhat-developer/service-binding-operator#234]
When `ServiceBindingRequest` is created first and then the application `Deployment` the operator keeps updating the `Deployment` and reconciling over and over again.

The `scenario-2` of the `test/e2e/servicebindingrequest_test.go` e2e test shows that by timing out waiting for the application. The `Deployment` development over time is shown [here](https://gist.github.com/pmacik/ee8089c4f31b3596f2ea596f63cc5611).

**Comment by pmacik** [comment]
According to the [event log](https://gist.github.com/pmacik/ee8089c4f31b3596f2ea596f63cc5611#file-events-log) the Pod is being created and deleted constantly

**Comment by pmacik** [comment]
@otaviof @sbose78 Shouldn't the application objects (such as the Deployment) be annotated with SBR annotations, as well as the backing service CRs?

I don't see the annotations on the application's `Deployment` while it is set on the `Database` (backing service CR)

**Comment by pmacik** [comment]
Wouldn't the annotations set on the `Deployment` stop the loop?

**Comment by isutton** [comment]
@pmacik at some point the update of the deployment with the labels was removed because OLM was the primary focus.

**Comment by sbose78** [comment]
Curious, why do you think the annotation would stop the infinite loop? Is something waiting on the annotation? 

We removed setting the annotation because trying to do so was causing an error, which was going into an infinite loop.

https://github.com/redhat-developer/service-binding-operator/pull/179

As far as I understood, the annotation on the Deployment would be needed if we are watching the Deployment object - which we aren't.

**Comment by pmacik** [comment]
> Curious, why do you think the annotation would stop the infinite loop? Is something waiting on the annotation?

I asked, in general terms... Ok, got it... Thanks for clarifying.

However, something still causes the issue.

**Comment by isutton** [comment]
I believe one of the reasons the Pods are being recreated is in this line:

https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/binder.go#L248-L248

The fact that every SBR reconciliation is producing a different value, it means that in case of a Deployment update, a new replica would be created. It is likely that if the value was stable at this point, the API server would ignore the update since the contents would be equivalent.

It may also indicate that a SBR is being reconciled more than once in a scenario one reconciliation is expected -- likely tests will be needed for this as well.
