### ISSUE TITLE
Separate API from operator to make it easier to be consumed by other tools?

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/service-binding-operator#375]
Trying to reuse the CR types in another project is quite difficult because of the huge number of dependencies that are brought along. Wouldn't it make sense to separate the API from the code to facilitate such reuse?

**Comment by sbose78** [comment]
Could you please share your usage details please?
( imports, etc..)

**Comment by metacosm** [comment]
I'm just trying to create a `ServiceBindingRequest` instance in my code. Trying to import that single type and retrieve the proper GVK for it using `SchemeGroupVersion`. The code is here: https://github.com/halkyonio/sbo-capability/blob/master/pkg/plugin/sbo/servicebinding.go

**Comment by sbose78** [comment]
Thanks, I would try ensuring that you are able to consume the API without having to separate it. We'll investigate asap.

**Comment by otaviof** [comment]
@metacosm, I think the correct [import](https://pkg.go.dev/github.com/redhat-developer/service-binding-operator/pkg/apis/apps/v1alpha1?tab=doc) for you application is:

```go
import "github.com/redhat-developer/service-binding-operator/pkg/apis/apps/v1alpha1"
```
In `v1alpha1` [directory](https://github.com/redhat-developer/service-binding-operator/tree/master/pkg/apis/apps/v1alpha1) we don't have any custom logic.

However, in [line 16](https://github.com/halkyonio/sbo-capability/blob/0ea891417fe99f5beb06ab0611398b252d8182b5/pkg/plugin/sbo/servicebinding.go#L16) of the example you've shared you are importing `servicebindingrequest` (controller) in order to acquire a single constant (`ServiceBindingRequestKind`), that's triggering importing a good chunk of SBO in your project.

So, for right now you can define that constant in your own project, and we should move that constant to either a standalone place, or inside [`v1alpha`](https://github.com/redhat-developer/service-binding-operator/tree/master/pkg/apis/apps/v1alpha1) folder (/cc @sbose78).

**Comment by metacosm** [comment]
> However, in [line 16](https://github.com/halkyonio/sbo-capability/blob/0ea891417fe99f5beb06ab0611398b252d8182b5/pkg/plugin/sbo/servicebinding.go#L16) of the example you've shared you are importing `servicebindingrequest` (controller) in order to acquire a single constant (`ServiceBindingRequestKind`), that's triggering importing a good chunk of SBO in your project.
> 
> So, for right now you can define that constant in your own project, and we should move that constant to either a standalone place, or inside [`v1alpha`](https://github.com/redhat-developer/service-binding-operator/tree/master/pkg/apis/apps/v1alpha1) folder (/cc @sbose78).

Yes, I understand that but that's exactly what I wanted to avoid (hardcoding the value). It would indeed make sense to move the constant to the API package instead.

**Comment by metacosm** [comment]
Note that I also need the status constants, which should also be moved to the API package, in my opinion.

**Comment by pedjak** [comment]
With #841 and #839 merged, the number of included dependencies for ServiceBinding API consumer got really minimal, it boils down to:

go.mod
```
require (
	github.com/redhat-developer/service-binding-operator v0.4.1-0.20210114171300-101f1fde7760
	k8s.io/apimachinery v0.17.4
)

replace k8s.io/client-go => k8s.io/client-go v0.17.4
```

for the following usage:
```go
import (
	"github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var sb = v1alpha1.ServiceBinding {
	TypeMeta: metav1.TypeMeta{
		APIVersion: "operators.coreos.com/v1alpha1",
		Kind:       "ServiceBinding",
	},
	ObjectMeta: metav1.ObjectMeta {

	},
	Spec: v1alpha1.ServiceBindingSpec{
	},
}

var gvk = v1alpha1.GroupVersionKind
```

IMHO, the issue can be closed now, please reopen if needed.
