### ISSUE TITLE
As developer, I want to read JSON format in binding secret, so that multiple services configuration/credential could well organized

### ISSUE THREAD

**Issue by ZhuangYuZY** [redhat-developer/service-binding-operator#388]
For multiple service binding in follow doc, in result secret, there are many env variables listed without organized. It will hard for developer to find right env variables and possible to duplicated env names (in most public cloud, service authentication/authorization is IAM based, service id and apikey will be very common env names for all public cloud services). You can say adding prefix before env name could help when multiple service binding, but flag tens env variables list still hard to use.
https://github.com/redhat-developer/service-binding-operator/tree/master/examples/multiple_services

Proposed solution:
  When in binding CRD, could we introduce a flag to indicate controller to generate only one env variable in result secret, named "VCAP_SERIVCES" (I copied the service binding env variable name from cloud foundry, we can have another better name). The value of the env variable is json string, example is following.  Then in application code, developer can easily to read one env variable and parser the JSON string to read key:value from each service instance.

Another benefit is for Cloud Foundry user, as JSON string VCAP_SERVICES for binding is same with CF service binding experience. So JSON string VCAP_SERVICES will help to migrate CF application with binding running on Kube/Openshift.

```
apiVersion: v1
data:
    "VCAP_SERVICES": {
                    "language_translator": [
                       {
                       "credentials": {
                          "apikey": ”xxx",
                          "url": ”xxx”
                          ……
                        }
                        }
                      ],
                       ”cloudant": [],
                       "cloud_object_storage": []
                   }
kind: Secret
metadata:
  name: helloworld-binding
  namespace: multiple-services-demo
  resourceVersion: "257567"
  selfLink: /api/v1/namespaces/multiple-services-demo/secrets/node-todo-git
  uid: 15aafcae-d334-49d8-be4c-2331f9c7cffe
type: Opaque
```

**Comment by otaviof** [comment]
Hello @ZhuangYuZY! Thanks for the feature suggestion, interesting use-case. Please, consider my comments below.

> For multiple service binding in follow doc, in result secret, there are many env variables listed without organized. It will hard for developer to find right env variables and possible to duplicated env names 

We are currently improving this area (cc @isutton, @Avni-Sharma), the variable names generated by SBO (Service Binding Operator) should never overlap each other, at least not in the secret generate by SBO.

And indeed, it can be hard to find the correct environment variable, since the amount of variables can be too much. To focus on those use-cases we've thought users would rely on [`CustomEnvVar`](https://github.com/redhat-developer/service-binding-operator/blob/6576a50c771b7bd554ba3374022fec6e82adbe75/examples/knative_postgresql_customvar/README.md), therefore, using Go Templates the users would untangle the data into key-value pairs, being free to use a templating language for that.

Do you think `CustomEnvVar` would help you out?

**Comment by duglin** [comment]
Hi @otaviof, while from a pure technical perspective `CustomEnvVar` can work, it requires quite a lot of work by the user. Superficially, that's a lot of typing, especially if there are several services being connected and each with many env vars. It also requires people to understand the structure of the resource's `status` section. One of the goals of Coligo is to try to hide the Kubernetes aspects from the user - either via the UI or simple cmd line. In order to use `CustomEnvVar` we'd be requiring people to learn about something that we're purposely trying to hide.

In fairness, yes putting all env vars into one env var via a JSON object requires users to learn about a new structure but being exposed to a single JSON object that is focused just on information that clients will need to connect to a service is something they should be able to easily wrap their heads around versus a Kubernetes object where they're now exposed to metadata, spec and status sections - that's a different level of complexity.

**Comment by ZhuangYuZY** [comment]
@duglin Agree with you. Thank you.

@otaviof, Thank you for your comment.
But I still think an JSON format string to contains all config/credentials is fair as option for multiple services binding case.
And you mentioned "We are currently improving this area (cc @isutton, @Avni-Sharma), the variable names generated by SBO (Service Binding Operator) should never overlap each other, at least not in the secret generate by SBO."  . Do we have an issue to track it ? I 'd like to understand more detail. Thank you.

**Comment by arthurdm** [comment]
hey @ZhuangYuZY  - multiple service configuration is something we're trying to define in the [service binding specification](https://github.com/application-stacks/service-binding-specification#mounting-binding-information).   It actually follows a similar convention from [buildpacks](https://github.com/buildpacks/rfcs/blob/master/text/0012-service-binding.md).  As illustrated [here](https://github.com/buildpacks/rfcs/blob/master/text/0012-service-binding.md#how-it-works), the industry is moving towards mounting of sensitive data instead of using env vars.  

You bring up a valid point in terms of migrating existing apps, so I wonder if there's a middle ground that can help with migration but still adopt best practices (e.g. perhaps an optional side container that would convert a spec-compliant mount of credentials into the legacy format).

**Comment by otaviof** [comment]
@duglin, @ZhuangYuZY, okay thanks for sharing the details about your use-case, I understand JSON would be better.

The reason I was asking about the "custom environment variable" is because from that feature, you can access all data that has been collected by the Service Binding Operator, and therefore, would be the equivalent of reading the JSON payload. 

Since "custom environment variable" has all the payload, it could very well implement more methods to transform that data. 

For instance:

```yml
spec:
  customEnvVar:
    - name: VCAP_SERVICES
      value: {{ to_json . }}
    - name: VCAP_SERVICES_SECTION
      value: {{ to_json .spec.some.cr.part }}
```

So, as an user you can use `to_json` in the whole tree (`.`), or choose an specific section to transform.

(/cc @sbose78, @isutton)

**Comment by ZhuangYuZY** [comment]
@otaviof  Thank you for your comment. I agree with that, we can extend `customEnvVar` to support `VCAP_SERVICES` with `JSON` format.  I think next we can think about how JSON looks like. We can take some examples to see comment.

@duglin From end user perspective, if CRD/Controller can support `VCAP_SERVICES`, then Coligo CLI can help to hide the `customEnvVar`.

**Comment by ZhuangYuZY** [comment]
@otaviof @sbose78 
To consider to_json for multiple backend services, I saw discussion in #356. Is it the direction we will use `id` to identify backing service instance in backingServiceSelectors?

**Comment by otaviof** [comment]
> @otaviof @sbose78
> To consider to_json for multiple backend services, I saw discussion in #356. Is it the direction we will use `id` to identify backing service instance in backingServiceSelectors?
> 
> For first thinking, if using to_json below, operator should loop for all backing service instances to generate json for it. What do you think ?
> 
> ```
> spec:
>   customEnvVar:
>     - name: VCAP_SERVICES
>       value: {{ to_json . }}
> ```

Our initial thought on how to express multiple backends would be:

```
<kind>.<name>.<attributes>
```

Where `kind` means the Kubernetes kind, as in `service` or `deployment`. After that, `<name>` is the actual Kubernetes resource name, followed by the `attributes`, which means anything collected on that specific resource.

For instance, having a service named "example", to express it as JSON, you would have:

```yml
spec:
  customEnvVar:
    - name: SERVICE_EXAMPLE_JSON
      value: {{ to_json .service.example }}
```

**Comment by ZhuangYuZY** [comment]
Understand your point. But what we need is put all backing service instances into on VCAP_SERVICE env variable. Thank you.

**Comment by otaviof** [comment]
> @otaviof Thank you. Understand your point. But what we need is put all backing service instances into on one VCAP_SERVICE env variable.

Okay, understood. In this case, you should simply use `{{ to_json . }}`. Dot (`.`) is the root of the tree and therefore it will render all data into a single JSON payload.
 
> I saw discussion in #356. Is it the direction we will use id to identify backing service instance in backingServiceSelectors? If so, could you do like `iterator` in to_json like below to loop all backing service instances ?

You would not need to loop in order to transform. Instead, you can select a section of the tree, that could either be subject to `range`, or, apply `to_json` transformation.
 
> ```
> spec:
>   customEnvVar:
>     - name: VCAP_SERVICE_1
>       value: {{ to_json iterator. }}
>     - name: VCAP_SERVICE_2
>       value: {{ to_json iterator.status.secretName }}
> ```

On the previous comment, I shared our plans to employ `<kind>.<name>.<attributes>`, which means the snippet bellow would look like the following:


```yml
spec:
  customEnvVar:
    - name: VCAP_SERVICE_1
      value: {{ to_json .service.one }}
    - name: VCAP_SERVICE_2
      value: {{ to_json .service.two.status.secretName }}
```

Please note the services here are named `one` and `two` respectively for simplicity.

Going deeper on how it works internally, the operator is collecting data as a `map[string]interface{}`, this map is then passed on to the template engine, in our examples you see are [Go Templates](https://golang.org/pkg/text/template/), which ships already with a number of [functions](https://golang.org/pkg/text/template/#hdr-Functions), and thus we need to think of a `to_json` new function.

For the record, we also have a request to support JSONPath (#352) as well.

**Comment by ZhuangYuZY** [comment]
@otaviof Understand your point, will discuss with team to see if to_json can satisfy our requirement. Thank you for your response.

**Comment by sbose78** [comment]
Brainstorming further:

Technically, this should also work right @otaviof @ZhuangYuZY 
```
spec:
  customEnvVar:
    - name: VCAP_SERVICES
       value: < Write out the entire vcap services json here >
```

( I know a lot of these might be messy, bear with us please )

**Comment by ZhuangYuZY** [comment]
Hi @otaviof and @sbose78 ,
   From code in master so far, it seems to support multiple backing services in backingServiceSelectors. But not for customEnvVar, if we have multiple backing services, the custom env var will be overwritten, using last backing service instance cr. What is the plan to support mutiple service instance cr for customEnvVar ? Because to-json implementation depends on it, I 'd like to ask team to submit PR for to-json.

   Another thing is format of to-json output, we will suggest following, I took IBM Cloud operator as example. Propose to add `backingServiceId` with `<group>.<kind>.<name>` for each backing service cr. What do you think ? 
```
VCAP_SERVICES=[
  {
    "backingServiceId": "ibmcloud.ibm.com.Binding.mytranslator-binding-1",
    "spec": {
      "serviceName": "my-translator"
    },
    "status": {
      "instanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:8b9b6da2-b594-47f2-8f33-1907f6797034::",
      "keyInstanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:8b9b6da2-b594-47f2-8f33-1907f6797034:resource-key:485b1173-8be1-4561-9243-817bae7f4452",
      "message": "Online",
      "secretName": {
        "apikey": "xxx1",
        "iam_apikey_description": "Auto-generated for key 485b1173-8be1-4561-9243-817bae7f4452",
        "iam_apikey_name": "mytranslator-binding",
        "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
        "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ef6a34810cbcd892507d3ebe01e3d95a::serviceid:ServiceId-3270a074-2c25-44d8-98c1-846cd8dcb312",
        "url": "https://api.us-south.language-translator.watson.cloud.ibm.com/instances/8b9b6da2-b594-47f2-8f33-1907f6797034"
      },
      "state": "Online",
      "status.secretName": {
      }
    }
  },
  {
    "backingServiceId": "ibmcloud.ibm.com.Binding.mytranslator-binding-2",
    "spec": {
      "serviceName": "my-translator2"
    },
    "status": {
      "instanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:c6c9be8e-68fe-4a17-8cfe-1c2c5f69dabf::",
      "keyInstanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:c6c9be8e-68fe-4a17-8cfe-1c2c5f69dabf:resource-key:00899b75-fa24-4eaa-b35d-f267c5f0c7df",
      "message": "Online",
      "secretName": {
        "apikey": "xxx2",
        "iam_apikey_description": "Auto-generated for key 00899b75-fa24-4eaa-b35d-f267c5f0c7df",
        "iam_apikey_name": "mytranslator-binding2",
        "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
        "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ef6a34810cbcd892507d3ebe01e3d95a::serviceid:ServiceId-74aad50c-8e8d-4255-90ae-589900cf30f4",
        "url": "https://api.us-south.language-translator.watson.cloud.ibm.com/instances/c6c9be8e-68fe-4a17-8cfe-1c2c5f69dabf"
      },
      "state": "Online",
      "status.secretName": {
      }
    }
  }
]
```

**Comment by qibobo** [comment]
@otaviof @sbose78 
In current code, the retriever.cache is a `map[string]interface{}` which only supports single backend service. And if I bind multiple services, it only lefts the last ones information as below:
```
{
  "spec": {
    "serviceName": "my-translator"
  },
  "status": {
    "instanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:8b9b6da2-b594-47f2-8f33-1907f6797034::",
    "keyInstanceId": "crn:v1:bluemix:public:language-translator:us-south:a/ef6a34810cbcd892507d3ebe01e3d95a:8b9b6da2-b594-47f2-8f33-1907f6797034:resource-key:485b1173-8be1-4561-9243-817bae7f4452",
    "message": "Online",
    "secretName": {
      "apikey": "xxx1",
      "iam_apikey_description": "Auto-generated for key 485b1173-8be1-4561-9243-817bae7f4452",
      "iam_apikey_name": "mytranslator-binding",
      "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
      "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ef6a34810cbcd892507d3ebe01e3d95a::serviceid:ServiceId-3270a074-2c25-44d8-98c1-846cd8dcb312",
      "url": "https://api.us-south.language-translator.watson.cloud.ibm.com/instances/8b9b6da2-b594-47f2-8f33-1907f6797034"
    },
    "state": "Online",
    "status.secretName": {
      
    }
  }
}
```

So to support multiple binding, what will the `retriever.cache` like? Do you have any proposal, code or PR for it? I did an update in my fork repo by changing it to a  slice `[]map[string]interface{}` and then could get an array result as Zhuang mentioned above.

**Comment by sbose78** [comment]
> From code in master so far, it seems to support multiple backing services in backingServiceSelectors. But not for customEnvVar, if we have multiple backing services, the custom env var will be overwritten, using last backing service instance cr. What is the plan to support mutiple service instance cr for customEnvVar ?

See https://github.com/redhat-developer/service-binding-operator/issues/356 
but TLDR 
https://github.com/redhat-developer/service-binding-operator/issues/396 should take care of it.

**Comment by sbose78** [comment]
> And if I bind multiple services, it only lefts the last ones information as below:

Yup, it overwrites, and that's a pending fix as per #396 .

**Comment by pedjak** [comment]
@ZhuangYuZY can this be closed now?

**Comment by ZhuangYuZY** [comment]
@pedjak It already address, close it.
