### ISSUE TITLE
How to use service binding operator in go code?

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#499]
In the [odo project](https://github.com/openshift/odo/), we're working on linking an Operator backed service with an application (https://github.com/openshift/odo/issues/2920). We intend to use the Service Binding Operator to do so.

My (probably naive) question is about using the SBO in our code. If I were to add dependency in glide or go.mod, what do you recommend I use? I'm asking because I see that last release of SBO happened in November 2019. I don't see any other release/tag in the repo. Among the active branches, I see a few patches or old branches (older than the latest release).

**Comment by DhritiShikhar** [comment]
@dharmit 

[1] There are already ongoing conversations for making github releases -> https://github.com/redhat-developer/service-binding-operator/issues/492#issuecomment-634088251
But we don't have anything planned for the same.

[2] A lot of changes have happened since November 2019, so yes we should make a release on github as soon as possible.

**Comment by DhritiShikhar** [comment]
@sbose78 @pedjak Can we draft a new release on GH?

**Comment by sbose78** [comment]
Yes, let's go ahead and do a release asap. Feel free to decide if any other fix needs to go in. The odo work is very critical and let's unblock it as soon as possible.

**Comment by DhritiShikhar** [comment]
@dharmit Here you go -> https://github.com/redhat-developer/service-binding-operator/releases

**Comment by dharmit** [comment]
Thanks for addressing this @DhritiShikhar :+1:
