### ISSUE TITLE
Support the spec  ServiceBinding CRD

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#587]
The [Service Binding Specification](https://github.com/k8s-service-bindings/spec) has created a [new CRD](https://github.com/k8s-service-bindings/spec/blob/master/service.binding_servicebindings.yaml) called `ServiceBinding`.   It was inspired by SBO's `ServiceBindingRequest`, but has certain restrictions and small tuning from the spec.  

This issue will track SBO's adoption of this CRD, and move SBO closer to spec compliance (along with #403 and #548).

For reference, [this repo](https://github.com/vmware-labs/service-bindings/releases/tag/v0.1.0) has already implemented support for this CRD.

**Comment by sbose78** [comment]
Ack.
We shall triage and evaluate which parts are reasonable to be adopted in the recent future.

**Comment by sbose78** [comment]
Arthur, 
Given that we are under feature freeze ( other than existing PRs ) till the September 15th release, could you help me with the following :

1) Feature comparison between things in Service Binding operator & the spec. 

2) If you were to have new contributions from your team, how would the development plan look like? Could you or someone from your team help with that?

I'll let the newer contributors make detailed proposals and drive the discussion.

Note, the September 15th release addreses

1) Our exploration with strimzi team and how the annotations/descriptors were shaped since then.

2) Multiple backing services and its impact on all features.

3) General stability.

**Comment by sbose78** [comment]
Here's a process to enable the enhancements to flow in
https://github.com/redhat-developer/service-binding-operator/pull/610

**Comment by arthurdm** [comment]
thanks @sbose78 

@arturdzm - can you please work on the proposal outlined above?

**Comment by sbose78** [comment]
Even better, the proposal process #610 has been merged, @arthurdm and @arthurdzm ( cc @scothis ), please feel free!

**Comment by baijum** [comment]
Are we going to call this Tech Preview in GA release?
