### ISSUE TITLE
Community Meeting - August 20, 2020

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#609]

**Comment by DhritiShikhar** [comment]
Meeting Mintues:

[1] #513 
@DhritiShikhar : Some volumemount issue on the PR.
@cdlliuy : https://github.com/redhat-developer/service-binding-operator/pull/513#issuecomment-677565211

[2] Breaking API changes:
@DhritiShikhar : This PR breaks API https://github.com/redhat-developer/service-binding-operator/pull/608 Most probably would be merged by next week. I will give a heads up to @cdlliuy on IBM slack channel before merging the PR

[3] update on backing service watcher:
@Avni-Sharma Can you give more information on this?
This is probably related to https://github.com/redhat-developer/service-binding-operator/issues/508

**Comment by Avni-Sharma** [comment]
For #508 The fix is in PR https://github.com/redhat-developer/service-binding-operator/pull/597 @cdlliuy If you can please manually try this once and provide feedback. Currently, I am trying to frame a set of acceptance tests for this. A requirement for this would be an app that consumes BOOTSTRAP_SERVICES. Please refer https://github.com/redhat-developer/service-binding-operator/issues/508#issuecomment-671788426

**Comment by Avni-Sharma** [comment]
Adding a video link for the same - https://youtu.be/E3SsHE7K9OQ
