### ISSUE TITLE
SBO does not automatically get latest CR changes

### ISSUE THREAD

**Issue by rawa-resul** [redhat-developer/service-binding-operator#970]
### What is the environment (Minikube, Openshift)?
Openshift 4.6.22

### What is the SBO version used?
0.7.1

### What are the steps to reproduce this issue?
  1.  In namespace 'A' have a CRD that provides bindings to SBO
  2. In namespace 'B' bind to SBO to get the service bindings from 'A'
  3. Make a change to the CR in namespace 'A'
  4. Check whether change from CR in 'A' has been picked up by SBO (automatically) in namespace 'B'

### What is the expected behaviour?
The SBO should pick up changes from the CRs automatically.

### What is the actual behaviour?
Initially the SBO creates all the right secrets and configmaps from the service bindings. However, if you make a change to those configs the SBO does not automatically pick this up unless you restart the SBO pod.

### Service Binding Operator Logs
No specific logs

**Comment by scottkurz** [comment]
I think I recreated this issue on 0.9.1.   Some details:

* I was only using a single NS 'A' for both the CR and SBO
* I was using 'odo' with the Dev4Devs PostgreSQL Operator annotated as described here:  https://github.com/OpenLiberty/application-stack-samples/tree/main/jpa   (the odo doc had a similar sample but it's in transition to a new home)
* The new/updated secret was not created after changing the CR spec in my OpenShift console and saving.
* I could workaround the problem by manually deleting the SBO pod.   My cluster would then create a new SBO pod and it would create the new secret (which in turn would cause my app pod to get restarted bound to the new secret).

**Comment by pedjak** [comment]
In order to achieve that in a generic way, SBO needs to watch for many many resources and we tried that in early phases, but performances and resource consumption on production clusters were far from great. Hence, in #903 we turned it off, until we are able to achieve that in a smarter way (see #846)

However, there is one scenario where updates are propagated:
* bind to [provisioned service](https://github.com/servicebinding/spec#provisioned-service) deployed within the same namespace as the application
* project bindings as files
